/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  name?: string;
  email?: string;
  favorites?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  createdAt?: string;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    options?: Array<{
      key?: string;
      value?: string;
      _key: string;
    }>;
    unitPrice?: number;
    price?: number;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  status?: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
  orderDate?: string;
  shippingAddress?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postal_code?: string;
    country?: string;
    phone?: string;
  };
  shippingMethod?: string;
  shippingCost?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ProductVariant = {
  _type: "productVariant";
  options?: {
    color?: Array<string>;
    size?: Array<string>;
    shoeSize?: Array<string>;
    ringSize?: Array<string>;
  };
  stock?: number;
  sku?: string;
  shippingTime?: "express" | "standard" | "economy" | "global";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  vendor?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "vendor";
  };
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  intro?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  variants?: Array<
    {
      _key: string;
    } & ProductVariant
  >;
  price?: number;
  discount?: number;
  currency?: "EUR" | "USD" | "GBP" | "CAD" | "AUD" | "AED";
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  minOrder?: number;
  reviews?: Array<{
    name?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    message?: string;
    rating?: number;
    date?: string;
    _key: string;
  }>;
  productDetails?: {
    characteristics?: Array<string>;
    weight?: string;
    material?: string;
  };
  freeShipping?: boolean;
  likes?: number;
  rating?: number;
  reviewCount?: number;
};

export type Vendor = {
  _id: string;
  _type: "vendor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  rating?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | User
  | Order
  | Category
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | ProductVariant
  | Product
  | Vendor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: sanity\helpers\index.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type == "product"] | order(name asc) {      ...,      vendor->{        _id,          _type,        name,        image      },      categories->{      _id,      title,      },       variants[]{        _key,        price,        stock,        options      },      "inStock": count(variants[stock > 0]) > 0,    }
export type PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  vendor: {
    _id: string;
    _type: "vendor";
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  intro?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  variants: Array<{
    _key: string;
    price: null;
    stock: number | null;
    options: {
      color?: Array<string>;
      size?: Array<string>;
      shoeSize?: Array<string>;
      ringSize?: Array<string>;
    } | null;
  }> | null;
  price?: number;
  discount?: number;
  currency?: "AED" | "AUD" | "CAD" | "EUR" | "GBP" | "USD";
  categories: null;
  minOrder?: number;
  reviews?: Array<{
    name?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    message?: string;
    rating?: number;
    date?: string;
    _key: string;
  }>;
  productDetails?: {
    characteristics?: Array<string>;
    weight?: string;
    material?: string;
  };
  freeShipping?: boolean;
  likes?: number;
  rating?: number;
  reviewCount?: number;
  inStock: boolean | null;
}>;

// Source: sanity\helpers\index.ts
// Variable: PRODUCT_SEARCH_QUERY
// Query: *[_type == "product" && name match $searchParam] | order(name asc)
export type PRODUCT_SEARCH_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  vendor?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "vendor";
  };
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  intro?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  variants?: Array<
    {
      _key: string;
    } & ProductVariant
  >;
  price?: number;
  discount?: number;
  currency?: "AED" | "AUD" | "CAD" | "EUR" | "GBP" | "USD";
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  minOrder?: number;
  reviews?: Array<{
    name?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    message?: string;
    rating?: number;
    date?: string;
    _key: string;
  }>;
  productDetails?: {
    characteristics?: Array<string>;
    weight?: string;
    material?: string;
  };
  freeShipping?: boolean;
  likes?: number;
  rating?: number;
  reviewCount?: number;
}>;

// Source: sanity\helpers\index.ts
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(name asc) [0]    {      ...,      vendor->{  _id,  _type,  _createdAt,  _updatedAt,  _rev,  name,  image,  rating},categories->{      _id,      title,      }, variants[]{        _key,        price,        stock,        options      },      "inStock": count(variants[stock > 0]) > 0,    }
export type PRODUCT_BY_ID_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  vendor: {
    _id: string;
    _type: "vendor";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    rating: number | null;
  } | null;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  intro?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  variants: Array<{
    _key: string;
    price: null;
    stock: number | null;
    options: {
      color?: Array<string>;
      size?: Array<string>;
      shoeSize?: Array<string>;
      ringSize?: Array<string>;
    } | null;
  }> | null;
  price?: number;
  discount?: number;
  currency?: "AED" | "AUD" | "CAD" | "EUR" | "GBP" | "USD";
  categories: null;
  minOrder?: number;
  reviews?: Array<{
    name?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    message?: string;
    rating?: number;
    date?: string;
    _key: string;
  }>;
  productDetails?: {
    characteristics?: Array<string>;
    weight?: string;
    material?: string;
  };
  freeShipping?: boolean;
  likes?: number;
  rating?: number;
  reviewCount?: number;
  inStock: boolean | null;
} | null;

// Source: sanity\helpers\index.ts
// Variable: PRODUCT_BY_CATEGORY_QUERY
// Query: *[_type == 'product' && references(*[_type == "category" && slug.current == $categorySlug]._id)] | order(name asc)    {      ...,      vendor->{        _id,          _type,        name,        image      },      categories->{      _id,      title,      }, variants[]{        _key,        price,        stock,        options      },      "inStock": count(variants[stock > 0]) > 0,          }
export type PRODUCT_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  vendor: {
    _id: string;
    _type: "vendor";
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  intro?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  variants: Array<{
    _key: string;
    price: null;
    stock: number | null;
    options: {
      color?: Array<string>;
      size?: Array<string>;
      shoeSize?: Array<string>;
      ringSize?: Array<string>;
    } | null;
  }> | null;
  price?: number;
  discount?: number;
  currency?: "AED" | "AUD" | "CAD" | "EUR" | "GBP" | "USD";
  categories: null;
  minOrder?: number;
  reviews?: Array<{
    name?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    message?: string;
    rating?: number;
    date?: string;
    _key: string;
  }>;
  productDetails?: {
    characteristics?: Array<string>;
    weight?: string;
    material?: string;
  };
  freeShipping?: boolean;
  likes?: number;
  rating?: number;
  reviewCount?: number;
  inStock: boolean | null;
}>;

// Source: sanity\helpers\index.ts
// Variable: MY_ORDERS_QUERY
// Query: *[_type == "order" && clerkUserId == $userId] | order(orderDate desc) {      _id,      orderNumber,      stripeCheckoutSessionId,      stripeCustomerId,      clerkUserId,      customerName,      email,      totalPrice,      currency,      status,      orderDate,      shippingAddress {        name,        line1,        line2,        city,        state,        postal_code,        country,        phone      },      shippingMethod,      shippingCost,      amountDiscount,      products[] {        _key,        quantity,        selectedSize,        selectedColor,        selectedShoesSize,        unitPrice,        price,        product->{          _id,          name,          images,          price,          currency,          slug        }      },      invoice {        id,        number,        hosted_invoice_url      }    }
export type MY_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  stripeCheckoutSessionId: string | null;
  stripeCustomerId: string | null;
  clerkUserId: string | null;
  customerName: string | null;
  email: string | null;
  totalPrice: number | null;
  currency: string | null;
  status: "cancelled" | "delivered" | "paid" | "pending" | "shipped" | null;
  orderDate: string | null;
  shippingAddress: {
    name: string | null;
    line1: string | null;
    line2: string | null;
    city: string | null;
    state: string | null;
    postal_code: string | null;
    country: string | null;
    phone: string | null;
  } | null;
  shippingMethod: string | null;
  shippingCost: number | null;
  amountDiscount: number | null;
  products: Array<{
    _key: string;
    quantity: number | null;
    selectedSize: null;
    selectedColor: null;
    selectedShoesSize: null;
    unitPrice: number | null;
    price: number | null;
    product: {
      _id: string;
      name: string | null;
      images: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }> | null;
      price: number | null;
      currency: "AED" | "AUD" | "CAD" | "EUR" | "GBP" | "USD" | null;
      slug: Slug | null;
    } | null;
  }> | null;
  invoice: {
    id: string | null;
    number: string | null;
    hosted_invoice_url: string | null;
  } | null;
}>;

// Source: sanity\helpers\index.ts
// Variable: RELATED_PRODUCTS_QUERY
// Query: *[_type == "product" && references($categoryId) && _id != $currentProductId] | order(name asc)[0...5] {      ...,      vendor->{        _id,          _type,        name,        image  },  categories->{      _id,      title,      }, variants[]{        _key,        price,        stock,        options      },      "inStock": count(variants[stock > 0]) > 0,      }
export type RELATED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  vendor: {
    _id: string;
    _type: "vendor";
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  intro?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  variants: Array<{
    _key: string;
    price: null;
    stock: number | null;
    options: {
      color?: Array<string>;
      size?: Array<string>;
      shoeSize?: Array<string>;
      ringSize?: Array<string>;
    } | null;
  }> | null;
  price?: number;
  discount?: number;
  currency?: "AED" | "AUD" | "CAD" | "EUR" | "GBP" | "USD";
  categories: null;
  minOrder?: number;
  reviews?: Array<{
    name?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    message?: string;
    rating?: number;
    date?: string;
    _key: string;
  }>;
  productDetails?: {
    characteristics?: Array<string>;
    weight?: string;
    material?: string;
  };
  freeShipping?: boolean;
  likes?: number;
  rating?: number;
  reviewCount?: number;
  inStock: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n    *[_type == "product"] | order(name asc) {\n      ...,\n      vendor->{\n        _id,\n          _type,\n        name,\n        image\n      },\n      categories->{\n      _id,\n      title,\n      },\n       variants[]{\n        _key,\n        price,\n        stock,\n        options\n      },\n      "inStock": count(variants[stock > 0]) > 0,\n    }\n  ': PRODUCTS_QUERY_RESULT;
    '*[_type == "product" && name match $searchParam] | order(name asc)': PRODUCT_SEARCH_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug] | order(name asc) [0]\n    {\n      ...,\n      vendor->{\n  _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  name,\n  image,\n  rating\n},\ncategories->{\n      _id,\n      title,\n      },\n variants[]{\n        _key,\n        price,\n        stock,\n        options\n      },\n      "inStock": count(variants[stock > 0]) > 0,\n    }': PRODUCT_BY_ID_QUERY_RESULT;
    '*[_type == \'product\' && references(*[_type == "category" && slug.current == $categorySlug]._id)] | order(name asc)\n    {\n      ...,\n      vendor->{\n        _id,\n          _type,\n        name,\n        image\n      },\n      categories->{\n      _id,\n      title,\n      },\n variants[]{\n        _key,\n        price,\n        stock,\n        options\n      },\n      "inStock": count(variants[stock > 0]) > 0,\n      \n    }': PRODUCT_BY_CATEGORY_QUERY_RESULT;
    '\n    *[_type == "order" && clerkUserId == $userId] | order(orderDate desc) {\n      _id,\n      orderNumber,\n      stripeCheckoutSessionId,\n      stripeCustomerId,\n      clerkUserId,\n      customerName,\n      email,\n      totalPrice,\n      currency,\n      status,\n      orderDate,\n      shippingAddress {\n        name,\n        line1,\n        line2,\n        city,\n        state,\n        postal_code,\n        country,\n        phone\n      },\n      shippingMethod,\n      shippingCost,\n      amountDiscount,\n      products[] {\n        _key,\n        quantity,\n        selectedSize,\n        selectedColor,\n        selectedShoesSize,\n        unitPrice,\n        price,\n        product->{\n          _id,\n          name,\n          images,\n          price,\n          currency,\n          slug\n        }\n      },\n      invoice {\n        id,\n        number,\n        hosted_invoice_url\n      }\n    }\n  ': MY_ORDERS_QUERY_RESULT;
    '\n    *[_type == "product" && references($categoryId) && _id != $currentProductId] | order(name asc)[0...5] {\n      ...,\n      vendor->{\n        _id,\n          _type,\n        name,\n        image\n  },\n  categories->{\n      _id,\n      title,\n      },\n variants[]{\n        _key,\n        price,\n        stock,\n        options\n      },\n      "inStock": count(variants[stock > 0]) > 0,\n      }\n  ': RELATED_PRODUCTS_QUERY_RESULT;
  }
}
